version: '3.4'

services:
  eureka-server:
    image: leobarreto/eureka-server:1.0.0
    container_name: eureka-server-container
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - hr-system

  api-gateway:
    image: leobarreto/api-gateway:1.0.1
    container_name: api-gateway-container
    ports:
      - "8765:8765"
    expose:
      - "8765"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system
  
  user-api:
    image: leobarreto/user-api:1.0.0
    container_name: user-api-container
    ports:
      - "8000:8000"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system
    
  payroll-api:
    image: leobarreto/payroll:1.0.0
    container_name: payroll-api-container
    ports:
      - "8100:8100"
    depends_on:
      - eureka-server
      - api-gateway
      - user-api
    environment:
      - EUREKA_URL=http://eureka-server:8761/eureka
    networks:
      - hr-system

networks:
  hr-system:
    driver: bridge